In [2]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [2]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

In [3]:
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [4]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [5]:
y

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [6]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [7]:
model

LogisticRegression(random_state=0, solver='liblinear')

In [8]:
model.fit(x, y)

LogisticRegression(random_state=0, solver='liblinear')

In [9]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(x, y)

In [10]:
list(model.intercept_)

[-1.046080667373841]

In [11]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')

In [12]:
titanic_train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [13]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [14]:
sex=list(map(lambda x : 1 if(x=="Male") else 0, titanic_train["Sex"]))

In [15]:
titanic_train['sex']= sex    
data=titanic_train[["Survived","Age", "Pclass", "sex", "SibSp", "Parch", "Fare"]]
data=data.dropna(axis=0)

In [16]:
data.describe()

Survived         Age      Pclass    sex       SibSp       Parch  \
count  126.000000  126.000000  126.000000  126.0  126.000000  126.000000   
mean     0.325397   28.141508    2.341270    0.0    0.706349    0.460317   
std      0.470393   14.613880    0.811544    0.0    1.131848    0.935100   
min      0.000000    0.830000    1.000000    0.0    0.000000    0.000000   
25%      0.000000   19.000000    2.000000    0.0    0.000000    0.000000   
50%      0.000000   26.000000    3.000000    0.0    0.000000    0.000000   
75%      1.000000   35.000000    3.000000    0.0    1.000000    0.750000   
max      1.000000   71.000000    3.000000    0.0    5.000000    5.000000   

             Fare  
count  126.000000  
mean    30.890476  
std     41.618958  
min      6.750000  
25%      8.050000  
50%     15.850000  
75%     34.584400  
max    263.000000

In [17]:
y=np.array(data["Survived"])

In [18]:
x=data[["Age", "Pclass", "sex", "SibSp", "Parch", "Fare"]]

In [19]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(x,y)

In [20]:
model.classes_

array([0, 1])

In [21]:
model.intercept_

array([1.01639364])

In [22]:
model.coef_

array([[-0.02657373, -0.38661991,  0.        , -0.26590347,  0.21666813,
        -0.00235167]])

In [23]:
pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [24]:
import statsmodels.api as sm

In [27]:
model=sm.Logit(y,x)

In [34]:
result = model.fit_regularized()

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.607667644602096
            Iterations: 18
            Function evaluations: 23
            Gradient evaluations: 18


/Users/sujatapal/Documents/anaconda/anaconda3/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1799: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/sujatapal/Documents/anaconda/anaconda3/lib/python3.8/site-packages/statsmodels/discrete/discrete_model.py:1852: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


LinAlgError: Singular matrix